### ISSUE TITLE
Changing Names ...

### ISSUE THREAD

**Issue by TiddlyTweeter** [Arlen22/TiddlyServer#10]
@Arlen22 In the docs you talk about the the "bundled version". But that does NOT express what it is or how it differs from the full version.

IMO I'd rename it the "TW Runner" ... (maybe later we can think up something more elegant :-)

**Comment by Arlen22** [comment]
Ok, I've updated the readme. Does that make it clearer?

**Comment by TiddlyTweeter** [comment]
Sorry for the delay in replying Arlen. 
Its clearer.
