### ISSUE TITLE
Worth adding "Getting Started" link to README?

### ISSUE THREAD

**Issue by phlummox** [Arlen22/TiddlyServer#102]
I thought this might be useful for newcomers, since I didn't initially notice the Getting Started Guide. Patch [here][patch], happy to do a pull request if you think this would be helpful.

[patch]: https://github.com/phlummox-patches/TiddlyServer/commit/2f90e5d13f1e2205d8f5c3849f7aa13395d06deb

**Comment by Arlen22** [comment]
Thanks, done.
