### ISSUE TITLE
Upload failed on linux with EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by ghost** [Arlen22/TiddlyServer#105]
When uploading a file with tiddlyserver interface on linux, the "EXDEV: cross-device link not permitted" error is raised and the upload failed.

When looking in /tmp, all the upload attempts are stucked here.

best regards
[settings.json.txt](https://github.com/Arlen22/TiddlyServer/files/5601929/settings.json.txt)

**Comment by Arlen22** [comment]
This definitely sounds like a bug. Thanks for bringing it to my attention.

**Comment by Arlen22** [comment]
Which is the version number of TiddlyServer you have installed? You can find it at the end of any directory index page.

**Comment by ghost** [comment]
TiddlyServer v2.2.0-alpha-7

**Comment by Arlen22** [comment]
Thanks for the feedback. I'm working on a fix for this right now.

**Comment by Arlen22** [comment]
Ok, I pushed an update to NPM. It should be fixed now.

**Comment by Arlen22** [comment]
It will now upload directly to the destination directory and then rename the file once it's done uploading instead of uploading to the temp directory.

**Comment by ghost** [comment]
It works like a charm. Thanks for your reactivity.

Great job ;)

**Comment by ghost** [comment]
Upload page still display TiddlyServer v2.2.0-alpha-7 but TiddlyServer v2.2.0-alpha-8 is actually in use
