### ISSUE TITLE
Server appears to load all tiddlers to client

### ISSUE THREAD

**Issue by TheYsconator** [Arlen22/TiddlyServer#110]
I have a wiki that is (all tiddlers combined) roughly 100MB. Naturally, these are not all text-tiddlers, but also zip files and images.

When visiting the wiki however, it appears as though all tiddlers are downloaded at once; not just the ones that are set as the Default Tiddlers'. For my server (which shouldn't be too bad) or (Caddy) config, this makes for my wiki no longer wanting to load. A white page loads instead. No error is shown in the browser's console.

If I remove some files, the wiki loads on occasion. However, if I then want to 'Save a snapshot for offline use' it crashes in the process.

It would be nice if there was a way to enable lazy-loading. I guess/ expect this would require some changes in the code of TW5 itself. If you expect that too, please let me know so I can check to see how feasible it would be to write a plugin that solves those requirements on TW5's end.

An alternative solution may be for me to look deeper into why exactly this file is a problem. I'm no expert on Caddy yet (and I still believe lazy-loading would be a nice solution), but please also let me know if you believe I should find my solution down that path.

**Comment by Arlen22** [comment]
You can set variables on the datafolder object in settings and these will be passed to each datafolder. 

```json
{
  "tree":{},
  "datafolder": {
    "root-tiddler": "$:/core/save/all-external-js or whatever you want",
  }
}
```

**Comment by TheYsconator** [comment]
Ah right! Thanks. Issue resolved on my part. (Partly because I can only half-fully test this, as I already mitigated the issue by reducing the wiki size. Don't hesitate to re-open if you think I've closed this too soon.)
