### ISSUE TITLE
Error while opening Tiddly Wiki

### ISSUE THREAD

**Issue by emlywhte** [Arlen22/TiddlyServer#111]
When I try and open my Tiddly Wiki from my saved resource in my google drive, it opens, however when I click on anything a screen pops up stating "There was an error downloading the file". This is a recent error and has previously been working fine for the past year. 

Thanks for any help in advance

**Comment by Arlen22** [comment]
Is this somehow related to TiddlyServer? Otherwise you're better off asking on the TiddlyWiki Google group. Do you have a backup you can go back to?
