### ISSUE TITLE
Creating folders through UI again

### ISSUE THREAD

**Issue by Iwaslazkis** [Arlen22/TiddlyServer#113]
Hey there, so I've been having a lot of fun setting up a TiddlyServer for myself (thanks Arlen!) and figuring out how to use it. I saw in issue #94 that there is a way to create new folders and upload files directly through TiddlyServer; and I'd like to do that since uploading files in TW throws me a 413 Too Large Error (even with small files).

![the UI options I want](https://user-images.githubusercontent.com/8428359/80632391-11bc1180-8a0c-11ea-9d6b-1c50336b1724.png)

I added the `localAddressPermissions` object with all of its values set to true like you mentioned there, but I didn't get any option to add folders or upload stuff. Did something change the beta version, or did I do something wrong?

Here's how my `bindInfo` section looks like in case that helps:
```json
{
    "bindInfo": {
        "bindAddress": ["127.0.0.1"],
        "localAddressPermissions": {
            "*": {
                "datafolder": true,
                "loginlink": true,
                "mkdir": true,
                "putsaver": true,
                "registerNotice": true,
                "transfer": false,
                "upload": true,
                "websockets": true,
                "writeErrors": false
            }
        }
    }
}
```

**Comment by Arlen22** [comment]
You can't add folders to groups, for obvious reasons, so that box will only show up if you're in a folder. 

`upload` enables uploading and `mkdir` enables creating directories.

**Comment by Iwaslazkis** [comment]
Oh, I didn't realize a group could be made up of paths from different folders! I thought they were literally a folder. I got it working now, thanks Arlen!
