### ISSUE TITLE
Centralized plugin and stylesheet management for multiple wikis

### ISSUE THREAD

**Issue by alexandergogl** [Arlen22/TiddlyServer#116]
First of all, thank you very much for developing TiddlyServer. For my wikis, I have completly moved to TiddlyServer.

However, I have several data folder wikis and synchronizing the plugins and stylesheets between them is a lot of manual work. I wonder if TiddlyServer provides a mechanism to read plugins and stylesheets from a central location. As far as I've understood it, Node.js seems to be capable of (see https://github.com/flibbles/tw5-relink#for-nodejs). The ideal case would be to control this in the settings.json file.

Best,

Alexander

**Comment by Arlen22** [comment]
TiddlyWiki data folders have the "includeWikis" field which can be used to include other data folders. That is generally how I handle this type of thing. https://tiddlywiki.com/#tiddlywiki.info%20Files
