### ISSUE TITLE
handle my 'tid' files by tiddlyserver and tiddlywiki-node  in the same time?

### ISSUE THREAD

**Issue by lifetraveler** [Arlen22/TiddlyServer#119]
hi!there are some questions when i start to use tiddlyserver.
before i use it ,i Setup a tiddlywiki nodejs server. now,my tiddlyserver's settings.json is  
{
  "tree": {
    "data": my old tiddlywiki folders,
    "workstuff": "../work",
    "user": "~/Desktop/random",
    "projects_group": {
      "tiddlyserver": "~/Desktop/Github/TiddlyServer",
      "material-theme": "~/Dropbox/Material Theme"
    }
  },

  "bindInfo": {
    "bindAddress": ["127.0.0.1"],
    "bindWildcard": true
  },
  "putsaver": {
    "backupFolder": "../backups" 
  },
  "$schema": "./settings-2-2.schema.json"
}

when i edit the same tid file, tiddlyserver  or my old tiddlywiki server can not change in the same time,the file's content are different,why? Tid file on the disk is same with my old tiddywiki server,where  is the file of tiddlyserver  edit ?

**Comment by Arlen22** [comment]
Two server instances cannot run the same data folder at the same time currently. This is exactly the same as running two tiddlywiki server instances with the same data folder. You would need a way for the instances to communicate changes to each other, and this would best be done within the existing framework of the file system adaptor, which can easily be extended to include two-way syncing as has already been done with the tiddlyweb adapter.
