### ISSUE TITLE
Cannot save single files on Android. Server Error. 

### ISSUE THREAD

**Issue by ibnishak** [Arlen22/TiddlyServer#12]
I opened a single file TW with the name "Thameem.html". When I try to save it, it says "Server error". Data folder TW works fine. Please look into it. 

Otherwise, damn fine work.

**Comment by ibnishak** [comment]
Saving worked when I removed the "backup.." line from settings.json. So all cool.

**Comment by Arlen22** [comment]
If removing the backup line helped, then it should have been a problem no matter where you opened it from. Usually, this happens if the backup folder cannot be written to. The backup folder is only used for single-file TiddlyWikis, thus data folders are unaffected. 

Hope that helps.
