### ISSUE TITLE
I create a subfolder to categorize some system tiddlers. But when they were modified, the position change to root tiddler folder!

### ISSUE THREAD

**Issue by joannepp** [Arlen22/TiddlyServer#120]
Can Tiddlerserver save the file in its subfolder position?

**Comment by Arlen22** [comment]
It should work exactly the same as the TiddlyWiki Node server. If you can do this properly with the Node server but not with TiddlyServer than could you explain in more detail how to do it in the Node server and I will attempt to find why it is not working the same in TiddlyServer.
