### ISSUE TITLE
New Version of TiddlyServer shipping latest TW version 5.2.1

### ISSUE THREAD

**Issue by JulioCantarero** [Arlen22/TiddlyServer#126]
TS is a great tool for TW, and I use it to launch my TWs and serve other files from the disk. However, it ships with TW5.1.23, although I have seen you made some commits to upgrade to 5.2.0.
I tried to figure out if upgrading the TW inside the TS is an option, but it is not easy (for me, I mean)
Could you please issue a new TS version with the latest TW5.2.1?
Thank you in any case for TS, still it is a terrific tool.

**Comment by Arlen22** [comment]
Done.

**Comment by Arlen22** [comment]
Actually, you'll need to manually update the dependency at the moment. I'll try to get to that soon.
