### ISSUE TITLE
SyntaxError: Unexpected token [

### ISSUE THREAD

**Issue by dixonge** [Arlen22/TiddlyServer#17]
when I run 'node server' from my TiddlyServer directory I get the following error:

```
/home/pi/code/TiddlyServer/server.js:151
        return server_types_1.obs_stat(state)(favicon).mergeMap(([err, stat]) => {
                                                                 ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by Arlen22** [comment]
What version of node are you using? You can find it by running `node -v`.

**Comment by dixonge** [comment]
4.2.1

**Comment by Arlen22** [comment]
Ok. V6 is the minimum that is supported by default since I compile for ES6. How did you install TiddlyServer? Git clone and npm install? Or did you download the bundle?

**Comment by dixonge** [comment]
git clone

evidently my node install instructions were old...if I update to 8.x will TS still work?

**Comment by Arlen22** [comment]
Node version 8 will work fine. Any Node version 6 or above should work fine.

**Comment by dixonge** [comment]
upgraded to 8.6 - now getting *different* error:

`Settings file: /home/pi/code/TiddlyServer/settings.json
The settings file could not be parsed correctly
SyntaxError: Unexpected string in JSON at position 93
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/pi/code/TiddlyServer/server.js:29:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
caught process uncaughtException
(node:9259) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by dixonge** [comment]
looks like my problem is a faulty install - getting errors when running ```npm install```

```npm ERR! Cannot find module 'internal/errors'```

**Comment by Arlen22** [comment]
Try downloading the latest Tiddlyserver-x.x.x-bundled.zip from https://github.com/Arlen22/TiddlyServer/releases and using that one. Not sure what the deal is, but that error looks like it is trying to use an internal node module that is no longer available. I'm guessing NPM itself isn't upgraded correctly. 

The `settings.json` error means there is a syntax error in settings.json. You can try using https://jsonlint.com/ to figure out what's wrong with the JSON.

**Comment by dixonge** [comment]
Finally uninstalled and reinstalled Node.js and npm successfully - downloaded the zipped version - npm install ran successfully - node server ran successfully

The only remaining issue is the location of the Public folder - there was no such folder in Raspbian and I was unsure where to put it - TS doesn't seem to be able to find it, but I don't know if that is a settings.json issue or if I just need to create a Public folder in a different location

**Comment by Arlen22** [comment]
Just change the path in settings.json to whatever you want it. Relative
paths are resolved relative to settings.json.

The read me on this project contains more examples of the settings.json.

**Comment by dixonge** [comment]
I eventually figured that part out - all is now well - thanks!
