### ISSUE TITLE
paths in "tree" not working?

### ISSUE THREAD

**Issue by ranmaru90** [Arlen22/TiddlyServer#18]
I have "TiddlyServer" and "TiddlyWikis" in the same path and here is my settings.json:

{
    "tree": {
        "alias": "../TiddlyWikis",
    },   
    "types":{
        "htmlfile": ["htm", "html"]
    },
    "username": "",
    "password": "",    
    "host": "0.0.0.0",
    "port": 8555,    
    "backupDirectory": ""
}

After running node server I got:

> Settings file: D:\Users\ranmaru90\Documents\Google Drive\Tools\TiddlyServer\sett
> ings.json
> The settings file could not be parsed correctly
> SyntaxError: Unexpected token } in JSON at position 55
>     at JSON.parse (<anonymous>)
>     at Object.<anonymous> (D:\Users\ranmaru90\Documents\Google Drive\Tools\Tiddl
> yServer\server.js:29:21)
>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)
>     at Function.Module.runMain (module.js:665:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:607:3
> caught process uncaughtException
> (node:3152) [DEP0013] DeprecationWarning: Calling an asynchronous function witho
> ut callback is deprecated.
> 

But if I let "tree" be an empty object, the it runs but without the list.

**Comment by Arlen22** [comment]
https://jsonlint.com/

You need to remove the comma at the end of the alias line.

**Comment by ranmaru90** [comment]
Gah, didn't see the comma there! Thanks, it's running now.
