### ISSUE TITLE
Please clarify how static  files get served

### ISSUE THREAD

**Issue by Mirodin** [Arlen22/TiddlyServer#19]
I am not sure if it is just me but I can not get the static file serve working. When I create a new wiki via `node tiddlywiki wiki --init server` TiddlyServer shows and handles everything just fine. However when I import my single file wiki (FF 57, you know) all links to my external images are broken.

My single file structure:
```
- wiki/
    - 20xx/
    - 2016/
    - 2017/
        - img1.jpg
        - img2.jpg
    - index.html
```

Inside the wiki links look like this `[img[2017/img1.jpg]]`. When I open a tiddler with images the server requests `/wiki/2017/img1.jpg` which looks right to me. But somehow this results in a 404 and I have no idea where to put my images.

What I tried (none did work):
```
- wiki/
    - 20xx/
    - 2016/
    - 2017/
        - img1.jpg
        - img2.jpg
    - tiddlers/
```

```
- wiki/
    - tiddlers/
        - 20xx/
        - 2016/
        - 2017/
            - img1.jpg
            - img2.jpg
```

```
- wiki/
    - tiddlers/
- 20xx/
- 2016/
- 2017/
    - img1.jpg
    - img2.jpg
```

I think I am missing a crucial thing here but I don't know where. The only thing that seems to work is importing a image via drag&drop and linking to the new tiddler (which creates the "image" tiddler and a `.meta` tiddler alongside. However I want my images in one place (sorted by year) and tiddlers in another. Maybe the documentation could clear this up as how to migrate to data folders with external images.

Thank you for your help and this great peace of work :)

**Comment by Arlen22** [comment]
The missing piece is that the pictures should be placed beside the wiki
folder, not inside it. Nothing can be served from inside the wiki folder by
TiddlyServer.

If relative links from imported tiddlers dont point to the same path as the
imported wiki would if situated beside the wiki folder then let me know.

**Comment by Mirodin** [comment]
Thanks for the fast reply. I am not sure I understand your last sentence...

As I wrote before I put the image folders next to the wiki folder (last listing) and TW requests `/wiki/2017/img1.jpg` which looks fine. However if I do it as above the path to the image does not resolve to a folder alongside the wiki folder - at least that is what my logic tells me since it requests a subfolder of `wiki` to be `2017` and a file `img1.jpg` inside that.

When I do as in my last listing the problem still persists :(

**Comment by Arlen22** [comment]
Hmm, this can be fixed. Although it will break all current wikis. I think I should add it as an option that can be disabled if desired. 

I would rather that it work as you are expecting that it should, since that would make import seamless.

**Comment by Mirodin** [comment]
Thanks for thinking about this. Since I want to migrate all my wikis to TiddlsServer/Node in the long, what would you recommend to do? Will you add a "relativ link fix". Or do I have to change my wikis (not that big of a deal with vim and regex).

But than there is still the question where to put my external files? Should I proceed to drag&drop my images so they will be "Tiddlers" of some form alongside the `.meta` file?

Sorry, lot of questions for you to answer but I want to do it only once and I want to do it "right".

**Comment by Arlen22** [comment]
I've added the feature to master, and you are welcome to test it out. I'm guessing a release will follow in the next week or so..

**Comment by Mirodin** [comment]
Well, I feel a bit stupid now but I can not get it to work. I copied the image folder in all three possible locations but it seems I am doing it wrong. I start the server via `node ./TiddlyServer/server.js` from within `tmp`.

![tiddlyserver](https://user-images.githubusercontent.com/2410346/32826700-bb5ef0f8-c9e9-11e7-93fb-6fba154227d4.jpg)

My settings.json:
```
{
    "tree": {
        "wiki": "../wiki"
    },
    "types":{
        "htmlfile": ["htm", "html"]
    },
    "username": "",
    "password": "",
    "host": "0.0.0.0",
    "port": 8080,
    "useTW5path" : false
}
```

**Comment by Arlen22** [comment]
I don't expect it to work inside wiki, but it should work beside it. Navigate to the picture directly in the directory listing and copy the path, then compare it to the relative link generated in TiddlyWiki. 

If you don't mind, you can post both of them here for my reference.

**Comment by Mirodin** [comment]
I just want clarify that the folders `2014`, `2015`, `2016` and `2017` are the image folders (forgot this in the previous post). However I still get 404 for every picture.

The paths:
- on my hard drive: `/Users/mirodin/Desktop/tmp/2014/img1.jpg`
- in terminal with `"useTW5path" : false`: `/2014/img1.jpg`
- in terminal with `"useTW5path" : true:` `/wiki/2014/img1.jpg`
- in FF inspector (img src): `2014/img1.jpg`

**Comment by Arlen22** [comment]
I'm sorry, I just noticed the problem now, you need to specify the parent
of the wiki folder as the folder to use so that TiddlyServer can find the
other folders.

Sorry for not catching this sooner.

On Nov 15, 2017 11:27, "Mirodin" <notifications@github.com> wrote:

I just want clarify that the folders 2014, 2015, 2016 and 2017 are the
image folders (forgot this in the previous post). However I still get 404
for every picture.

The paths:

   - on my hard drive: /Users/mirodin/Desktop/tmp/2014/img1.jpg
   - in terminal with "useTW5path" : false: /2014/img1.jpg
   - in terminal with "useTW5path" : true: /wiki/2014/img1.jpg
   - in FF inspector (img src): 2014/img1.jpg

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Arlen22/TiddlyServer/issues/19#issuecomment-344647563>,
or mute the thread

**Comment by Mirodin** [comment]
Ah, now it works, thank you very much for taking the time to help me :)
Just out of curiosity, would it be smarter in the long run to add new pictures as "normal" Tiddlers (which creates them with a second `.meta` Tiddler?

**Comment by Mirodin** [comment]
Ok, I give up... Maybe I am too stupid to understand it but the behaviour is not consistent in my opinion. When I set `uaseTW5path` to `true` and start the server from the TiddlyServer dir (which is alongside the wikis folder) it shows the images. The next time I start the server, the images are gone. If I start the server from the parent directory (of tiddlyserver and the wikis folder), there are no images whatsoever. If I restart the server from within TiddlyServer folder with `useTW5path` set to `false` the images show up and are gone after I start from the parent directory.

Does TiddlyServer resolve the paths relative to the settings file even though I specify an absolute path? Maybe I am just to dug up into this but I really lost the hang for the path resolve for my static files. Could you give me an example config alongside a folder structure that is supposed to work as I feel I tried every possibility and still messed everything up. Sorry for all that trouble with me :(

**Comment by Arlen22** [comment]
Ok, start from the TiddlyServer folder. 

Any paths in settings.json are relative to the settings.json file. The directory you start from is ignored when finding the tree paths, but it is used by the program. 

```json
"tree": { "mywikis": "../../tmp" } 
```

**Comment by Arlen22** [comment]
Set `useTW5path` to false.

**Comment by Mirodin** [comment]
Now it works, thank you so much for your patience. :)
So I have to create a parent directory for every wiki where I put the actual wiki alongside the image folders, right?

**Comment by Arlen22** [comment]
Short answer, Yes.

Obviously multiple wikis can reference the same images folders.
