### ISSUE TITLE
What is TiddlyServer?

### ISSUE THREAD

**Issue by willwray** [Arlen22/TiddlyServer#2]
The announcement on tiddlywiki google groups didn't tell me concisely what this is
https://groups.google.com/d/msg/tiddlywiki/HF1XMIdQyss/u8vBbrbLDAAJ
Following the link to this GitHub repo, the Readme gives Installation, Benefits and Features
but doesn't say what it is!!!
Please put a paragraph of description:
what does it do
how does it differ from node.js tiddlywiki
etc

**Comment by Arlen22** [comment]
Done, how's that

https://github.com/Arlen22/TiddlyServer/blob/master/README.md

**Comment by willwray** [comment]
Fantastic. Really well written. The description leaves me smiling. Now I know exactly what it is.
TiddlyServer landing page is now better than the vast majority of GitHub project pages.
Thanks for sharing it. Consider the issue closed.
