### ISSUE TITLE
TiddlyServer (Source Code version) shows TiddlyWiki version 5.1.14 even though 5.1.15 has been installed instead

### ISSUE THREAD

**Issue by JulioCantarero** [Arlen22/TiddlyServer#20]
Hi,

**Maybe this is not a bug, as I have tampered with TiddlyServer to run TiddlyWiki version 5.1.15**, and the latest TS version still uses 5.1.14. But just in case TS can be improved to be TW5 version agnostic.
I am using TS Source Code. I downloaded the ZIP, unpacked it in my Windows PC, changed the `package.json` to make it dependent on TW version 5.1.15 rather than 5.1.14, and run `npm install`. Then I moved the `tiddlywiki` directory in `node_modules` up in parallel to `node_modules` as described in the instructions in **Installation** -> **Source Code Version**
I reused `settings.json` that I was already using with TS 2.0.6, and launched TS. TS is serving local files and a couple of TW folders. Everything worked fine, and I could check that TiddlyWiki had some of the new 5.1.15 features (e.g. new "Explorer" tab to "More" sidebar), but the TW version in the settings read `5.1.14`.
What is the reason for this inconsistency?
It is not a big deal, but I do not understand why TS used in Source Code has to be linked to a particular TW version.
Thank you.

**Comment by Arlen22** [comment]
This is a bug, I think, but everything should still work correctly.

**Comment by Arlen22** [comment]
Ok, I think this is fixed now. The TiddlyWiki bundle is now included in the repo. 

Note to self: The nexe builds will still have trouble, so I'm going to leave this open for now.

**Comment by Arlen22** [comment]
Closing because the nexe builds contain everything they need.
