### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by RayBB** [Arlen22/TiddlyServer#30]
Hello,

Thanks so much for making this great program. I've found it really useful and I hope to see it grow and keep doing well. As such, I was wondering if there's any way you could use help on this repo? I'm gonna have some free time the rest of this month and would love to contribute. I'm quite familiar with node and have used typescript before so I should be able to jump in without too much trouble.

I have a few ideas for things that might be helpful but I'd like to know what your priorities for the repo and what would be most useful to you.

Let me know! Thanks

**Comment by Arlen22** [comment]
I think the next project calling for attention would be a settings interface. If you are familiar with HTML/CSS/DOM, you would be welcome to work on that. I thought of using AngularJS (Angular V1) for the interface. Is this something you would want to take on? I am thinking of doing the heavy lifting in the client and just posting the finished JSON to the server. 

We could also add a few more authentication options, and support HTTPS server. Both of these would get their own property in `settings.json`. That's really all I have on my plate right now. 

The `server-api.js` file is kind of a mess right now. I'm working on writing better functions for it, which I'll probably take care of myself.

**Comment by Arlen22** [comment]
What are your ideas? I'm interested to hear them.

**Comment by RayBB** [comment]
I was thinking of having a setup script that could configure the setting but having a web interface for it is even better and I would be happy to work on that. I'm not too familiar with AngularJS but I think Vue would be a good candidate as well? Either way I could work on that.

I'm not too familiar with the authentication options either.

Some ideas I had for improvements:

* Way to create new wiki from withing the UI (could go on setting pages)
* One click install script (so they wouldn't have to manually configure/create a wiki) but that also goes closely with the UI.
* It might be useful to make a docker container
* Maybe update the documentation to look a bit more like [this](https://github.com/request/request#requestoptions-callback) for the settings 
* It would be good to track which versions of dependencies are being used in case of vulnerabilities and to know if they make breaking changes. Could use NPM to install them I don't know if there's some downside to this that I'm not seeing because I'm on Linux. For example, right now

**Comment by Arlen22** [comment]
I would like to put the functionality to create new wikis and upload files in the directory index. You are welcome to go ahead and code that. 

If you have a better way to write the docs, I'm always open, but I'm better at long-form explanations. So if you want to take it and condense it, you're welcome to.

I think the settings panel should come before any install scripts that way we can use it as part of the install process. But I like the idea of adding install scripts. 

What I know about the dependencies is that we are at node >=6, TiddlyWiki 5.1.15, WS something, and RxJS 5.4.3.

I think working in TypeScript and compiling to Javascript is good. Vue.js is fine. Looking forward to seeing what you come up with.

**Comment by Arlen22** [comment]
It looks like the settings panel is the biggest feature we need right now. If you want to do that, that would be great.

**Comment by RayBB** [comment]
I'd put a couple hours into working on it last week.
Right now it's basic and not doing any validation. I'm still trying to figure out a good way to do the folder settings since they can nest. Any ideas on that would be great.
But here's what I have so far. I can put it on github if you want.
![image](https://user-images.githubusercontent.com/921217/34322876-69f0fa6e-e801-11e7-8e26-5d51485d387a.png)

**Comment by Arlen22** [comment]
I think it would be best to have the user copy and paste the file paths
into the relevant fields (such as the tree and backup), and then
immediately check the path server-side and warn the user if there is a
problem.

This should not be a security problem because the settings panel server
will only be bound to IP 127.0.0.1 anyway, but it is something we should
keep in mind.

The tree should be a nesting layout that has elements that are either
simple or complex. The simple elements would be a key-value pair of text
fields, and the complex would have the same key field, but instead of the
value, it would have controls to add simple and complex child elements. The
key field should probably have a pencil icon or the like that you click to
edit the key, that way it's harder to change.

**Comment by Arlen22** [comment]
If you have another idea you want to try, go for it. That's just what I see
in my mind, but I'm sure it could be improved.

**Comment by RayBB** [comment]
I've been spending a little while now and then working on it but unfortunately I didn't get it finished.
I'll be leaving the country for a month and won't be able to work on it by then.

Basically the form is setup (except the directories) and the data is bound with vue.
I was thinking of using vue-validate but didn't get around to quite setting it up.

Hopefully this can be of some use to you. Hope you have a happy holidays!

[tiddlyServerGUI.zip](https://github.com/Arlen22/TiddlyServer/files/1596390/tiddlyServerGUI.zip)
