### ISSUE TITLE
Cannot start server: address in use?

### ISSUE THREAD

**Issue by PlaidPhantom** [Arlen22/TiddlyServer#31]
I'm trying to set up TiddlyServer on a home file/web server I have running Ubuntu 16.04. Whenever I try to start TiddlyServer I get an error message stating that my address is in use. I've verified the port is available both via netstat and by starting basic web servers on it, e.g. `python3 -m http.server 8083`. Any recommendations? I've tried installing both from the release bundle as well as cloning the repo directly.

The error: 
```
Settings file: /opt/tiddlywiki/settings.json
{ Error: listen EADDRINUSE 0.0.0.0:8083
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8083 }
caught process uncaughtException
closing server
```

My settings.json:
```json
{
        "tree": {
                "data": "/files/tiddlywiki"
        },
        "username": "[...]",
        "password": "[...]",
        "host": "0.0.0.0",
        "port":8083
}
```

**Comment by RayBB** [comment]
Have you tried running it as sudo?

Also, you could try putting your server's address instead of 0.0.0.0

**Comment by PlaidPhantom** [comment]
I have been running as sudo; sorry I forgot to mention that.

Putting in my server's IP address does work. Though now that I think of it, I probably need to just use 127.0.0.1 since I'm planning to put this behind a proxy.

Thanks for the fast response!

**Comment by Arlen22** [comment]
In that case, it is possible that there is another process listening on that port on a certain interface or IP address, but I don't know for sure what the problem is. However, this would be a Node-related problem and not a TiddlyServer problem specifically, so you can research it under "Node HTTP server cannot bind to 0.0.0.0" if you like.
