### ISSUE TITLE
Make backupDirectory unique for each served single file TiddlyWiki

### ISSUE THREAD

**Issue by garu57** [Arlen22/TiddlyServer#35]
Given that i'm completely new both to node.js and TiddlyWiki pls forgive me if i'm telling some oddity.

I'm still experimenting to see what kind of beast i've got (syntax, macros, widgets and mostly its philosophy that i don't yet completely grasp)  and i found really useful making one or more copy of a master wiki file and apply different changes to the different copies just to see the differences, then apply what i like most to the master  copy.
Then i delete the copies and make them new from the master with the same names (so i don't have to change settings.json)  and restart the cycle.

The problem is that when i delete a copy, the unique backupDirectory remain polluted with backups that are no longer usable and must be deleted manually.

Would it be possible to have the backupDirectory relative to the tree so that each single  file instance can have its own?

This would help at least in two ways, one, with this usage pattern, i could delete with a single action both the instance and the backups, second having the each backupDirectory  together with its file instance will allow to backup easily them together.

Thanks,
Gabriele

**Comment by Arlen22** [comment]
It is possible that in the future I could allow a backup folder to be
specified for each tree item. I will keep that in mind. Currently it is not
possible.

I would like to mention that you can specify a folder in the tree instead
of just a file, as it seems you have done, which then allows you to serve
anything in that folder.

**Comment by garu57** [comment]
Thanks, i tried using folder but i see there the behavior is completely different and as far as i understand backupDirectory is not applicable there.

I plan to use TiddlyWiki as a companion notebook of Jabref and Zotero for literary research and it will end containing a huge amount of data scattered on many different wikis, so before filling it with real data i want to be sure to have explored every single facet of it's behavior.

Now i'm stressing single file wikis, then will do the same on folder wikis. I need to be sure that's rock solid and i don't risk to loose data in any circumstances.

Anyhow thanks for your attention,
Gabriele

**Comment by Arlen22** [comment]
Actually, I'm referring to folders containing multiple single file wikis. If you specify a folder path instead of a file path in `settings.json` it will serve all the single file wikis AND data folders found in that folder. So you can have multiple single file wikis in the folder and just specify the whole folder instead of each individual wiki. You can also have multiple data folders (any folder containing a `tiddlywiki.info` file) in the folder. Of course, you can have both in the same folder.

**Comment by garu57** [comment]
Wow! That's powerful! I didn't got it.
As i said in my first post, i don't yet really grasp the "philosophy" behind this object. All the wikis i tried are php and a lot more rigid in structuring data, but this, as Ruston said, is something completely different. What really fascinated me from the beginning is the apparent simplicity by which once you have your data, you can build multiple "knowledge" paths through them and i'm looking for the magic "click" on this.

Anyhow, in the meanwhile, i solved another small problem. I don't like products that mix installation files with runtime byproducts, but fortunately with a rapid look at the code i saw that settings.json can be passed as an argument to the server, so now i have a wiki root dir with settings.json using only relative paths, backupDirectory and all the wiki folders and now i can move the server installation to a read only zone.

Thanks,
Gabriele

**Comment by Arlen22** [comment]
A backup folder may now be specified for each tree item in version 2.1. The documentation I am writing will include instructions for this.
