### ISSUE TITLE
Some clarifications about version and behavior

### ISSUE THREAD

**Issue by garu57** [Arlen22/TiddlyServer#36]
Hi Arlen,
sorry to bother you again, but now i'm completely confused.
Can you help me understanding if i'm doing something wrong?

1. commits in github say that the package was updated for 5.1.15, but all plugins.info into `tiddlywiki\plugins\tiddlywiki` are still marked 5.1.14

2. if i open a datafolder and download in local the browser content, indeed i see in the file that the `<div>` are all marked `version="5.1.14"`

3. if i throw away the bundled `tiddlywiki` and substitute it with the content of TiddlyWiki5-5.1.15, now i obtain a file with `<div>` marked as `version="5.1.15"`

4. the `tiddlywiki\core` content is completely different from TiddlyWiki5-5.1.15 content. Did you pack all the original content into that single `pluging.info`?

5. in the github readme you say "Loads data folders using a certain core/boot version (currently whatever gets installed with npm install or the bundled version if you use that)" but as far as i understand this does not correspond to real behavior.

6. actually as far as i could understand node.js is not booting the original `tiddlywiki\boot\boot.js` but a heavily modified version of it in `src\boot.js`. Why and what are the differences in behavior?

7. i also installed TiddlyWiki5-5.1.15 with `npm` but i didn't find any way to have TiddlyServer using it. If there is a bundled version it uses it, if i remove the bundle the server crashes.

Thanks, Gabriele

**Comment by Arlen22** [comment]
What version of TiddlyServer are you using? To upgrade to the latest version, just download it from the releases page, unzip it, and copy settings.json in from the old install. After that, it should say 5.1.15.

**Comment by garu57** [comment]
Latest release 2.0.11 (https://github.com/Arlen22/TiddlyServer/archive/2.0.11.zip).
Tried also to download the repo (https://github.com/Arlen22/TiddlyServer/archive/master.zip) but the content is the same.
Just as an example look at https://github.com/Arlen22/TiddlyServer/blob/master/tiddlywiki/plugins/tiddlywiki/async/plugin.info and you will see the following content:
`{"title":"$:/plugins/tiddlywiki/async","description":"Wrapper for async.js by Caolan McMahon","author":"JeremyRuston","core-version":">=5.0.0","list":"readme license","version":"5.1.14",...`
The rest of the plugins are all `5.1.14`.

**Comment by Arlen22** [comment]
Ok, I just checked and it appears to be 5.1.15 code. I do see the 5.1.14 version number, but that is not in the TiddlyWiki core data so it may come from package.json and I may have used an incorrect package.json. However, the core code is 5.1.15.

And yes, there is a feature in the bootloader which loads tiddlers from the plugin.info file as well, which significantly cuts down on first-load times when opening a data folder in tiddlyserver, since it needs to load every file in core for every data folder you open. So loading exactly one file per core/plugin/theme/language really saves time.

**Comment by garu57** [comment]
Thank you for the clarification, now i understand how it works.
I'm going to close the issue.

Regards,
Gabriele
