### ISSUE TITLE
Cannot link to files uploaded added through browser

### ISSUE THREAD

**Issue by teun95** [Arlen22/TiddlyServer#39]
I don't seem to be able to link to files in tiddlers that I attached through tiddlywiki.

I attach a file to my wiki by dragging it into the browser window. It then creates a new tiddler and the file appears in my tiddler folder. When I create a new tiddler and link to the file `[ext[mytiddlywiki/tiddlers/testfile.zip]]` the browser can't find the file and I get an error.

My directory is `../` and my tiddlywiki is located in `TiddlyServer-master/mytiddlywiki`. Relative linking to files located in TiddlyServer-master works without problems, but files located in `TiddlyServer-master/mytiddlywiki/tiddlers` does not work.

I work with relatively large files that are unsuitable for viewing in tiddlywiki. Ideally I would want to be able to drag them into tiddlywiki and easily link to them. If I understand it correctly that should be possible with tiddlyserver. Am I correct and is the described issue something I can solve?

PS I am hosting Tiddlyserver on my vps, hence the need to do everything through the browser.

**Comment by Arlen22** [comment]
There are two options. The first is if someone makes a plugin that allows attachments in the TiddlyWiki server, and the second is if I add an upload option in the browser. Both of those are probably coming in the near future.

**Comment by Arlen22** [comment]
Turned out to be quite simple

https://github.com/Arlen22/TiddlyServer/releases/tag/2.0.12
