### ISSUE TITLE
Suppressing HTTP logging?

### ISSUE THREAD

**Issue by symposion** [Arlen22/TiddlyServer#41]
Hi, thanks for all your work on this - it's a great tool! I was wondering, is it possible to suppress all the HTTP logging that TiddlyServer spits out? I'm running it as a systemd user service now and I'd rather that the logs didn't get filled with protocol debugging. I've tried setting debugLevel to a higher number but it doesn't seem to make any difference...

Cheers,

**Comment by Arlen22** [comment]
Thanks for the suggestion. This is now in master.
