### ISSUE TITLE
Problem errno: EADDRINUSE when binding to 0.0.0.0

### ISSUE THREAD

**Issue by khomphos** [Arlen22/TiddlyServer#43]
Hey there, 

Thanks for making this great tool. 

I tried to run with a bind on 0.0.0.0 inside of a docker container but I kept getting the following error regardless of what port I put: EADDRINUSE 0.0.0.0.

I'm not sure if I'm doing something silly but what I've had to do to work around this is comment out line 151 in server.js as it seems that you do a double bind there if the settings.host is not 127.0.0.1, I guess you meant to do the opposite?

Thanks!

**Comment by teun95** [comment]
I had exactly the same problem though it was not in docker but on Ubuntu server 16.04. In the end I ended up using my internal IP, but 0.0.0.0 would have been better. Does this mean 0.0.0.0 is meant to work?

**Comment by bars0um** [comment]
As far as I know, 0.0.0.0 means that the server will respond to any requests coming to any interface on your system that is reachable by the network. For something keeping your notes and information it is less than desirable to do this I would say. If you have to run that way (docker would not work with localhost) then you should ensure that the published port is blocked by your host's firewall...

**Comment by Arlen22** [comment]
I never thought this would be a problem, but in the latest versions there
is an option to disable this and treat all requests as originating from the
network (affects how certain permissions are set).

Set _disableLocalHost in settings.json to true to skip the whole double
attachment thing. This also means that only the allowNetwork property will
be used.

**Comment by Arlen22** [comment]
I'm curious if this solved the problem for you all and if you have any additional questions before I close this issue.

**Comment by ofthedove** [comment]
I just experienced this on a Ubuntu 16.04.5 LTS server with TiddlyServer 2.0.14

I'm intentionally opening the server to share with some friends, so using localhost wasn't an option.

Setting _disableLocalHost solved the issue for me. Thanks!

**Comment by bars0um** [comment]
Yep seems to work for me...

**Comment by Arlen22** [comment]
The extra localhost bind is now default off instead of default on.
