### ISSUE TITLE
Files being duplicated

### ISSUE THREAD

**Issue by SFxInfo** [Arlen22/TiddlyServer#44]
Hello

Why files are duplicated when I update data in my tiddlywiki ?
---
$_StoryList.tid 
$_StoryList 1.tid
---
This is the case for system tiddlers and mine.
This my first in GitHub so sorry if this space isn't made for it.

Best regards

**Comment by Arlen22** [comment]
Are you running more than one instance of TiddlyServer? Either on the same computer or on more than one?

**Comment by SFxInfo** [comment]
I tried after creating a new one and I opened it only in one tab. 
This project is installed in a Linux server. Could it be from file rights ? Do the files need the execute right ? 
---
Hum ! I remember now ! 
I saw a text (of you I think) that spoke of this problem. You can not run multiple processes. I did four to test the performances ^^
Am I talking about the same thing as you ?

**Comment by SFxInfo** [comment]
I think yes. It works well now. Thanks for your help. I'll use it and hope it will be my favorite to do what I need.

**Comment by Arlen22** [comment]
That is the only reason I know of why the story list tiddler would be handled in this way, so I am going to close this.
