### ISSUE TITLE
Saving a local copy of stand-alone file?

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#47]
Currently if you are serving up a data tiddler you can click the "save" button and get a local, stand-alone TW. But this feature doesn't seem to work when serving up a stand-alone file. This would be useful, for instance, if you were on a mobile device and wanted a quick copy before leaving your local network. This would be useful even though the "downloaded" file is not in the exact home directory that you would usually use. 

Thanks!

**Comment by Arlen22** [comment]
Make a button that sends the tm-download action.

**Comment by Arlen22** [comment]
Also, I just thought about it that you can always save from the directory listing! I don't know why I didn't think to mention that before. Just right click (or long press) then download the file.

**Comment by Marxsal** [comment]
If anyone is interested, here is the code I'm using:

`<$button class="tc-btn-big-green">
<$action-sendmessage $message="tm-download-file" $param="$:/core/save/all" filename="index.html"/>
<<lingo Full/Caption>> {{$:/core/images/save-button}}
</$button>
`
