### ISSUE TITLE
PDF files don't serve to local network devices

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#48]
On remote devices (e.g. one's using the local network) PDF's don't seem to serve. Tested on Linux and Windows (7).  They do serve on the local server itself, just not on the network.

**Comment by Arlen22** [comment]
Can you post the console output or email it to me directly? This will help
me to understand what is going on.

**Comment by Marxsal** [comment]
Hi Arlen,
Thanks for your response. I just realized that the problem is that all the tablets I have access to are out of date and/or don't support PDF in the browser session. I'll close this issue now. Thank you. -- Mark
