### ISSUE TITLE
I am now recieving 412 Errors again despite an etag or 3 then 8

### ISSUE THREAD

**Issue by AnthonyMuscio** [Arlen22/TiddlyServer#49]
Arlen,

Suddenly I am getting 412 errors as below on the console, which stop me saving the whole wiki, on more than one TiddlyServer served wiki. I am using latest general release FireFox and I recently re-installed TiddlyServer-2.0.14 

```
412 ifmatch "1125899906917436-7763470-1540777282000"
412 etag "1125899906917436-7810180-1540777455000"
412 caused by difference in size
412 caused by difference in modified
```

In this case it seems to be a size error. My Single File Wiki is currently less than 8MB in size.

I will refresh the browser and restart my Windows 10 desktop to see if this helps and will add a comment if it does not reoccur.

**Comment by AnthonyMuscio** [comment]
Re-occuring on all TiddlyServer served Wikis.

Why change now I am not sure,

```
{
    "tree": {
		"Instances": "C:\\Data\\TW5\\Instances",
		"PSaT Business": "C:\\Data\\TW5\\PSaT",
		"PSaT Development": "C:\\Data\\TW5\\PSaTDev",
		"Development": "C:\\Data\\TW5\\Development",
		"EmptyWikis": "C:\\Data\\TW5\\EmptyFiles",
		"Clients": "C:\\Users\\antho\\Documents\\Business\\PSaT\\Clients",
        "WebDav": "C:\\Users\\Public\\Documents\\tw",
	    "Node": "C:\\Data\\TW5\\NodeJS",
        "Editions": "C:\\Data\\TW5\\editions",
		"Pictures": "C:\\Users\\antho\\Pictures\\TiddlyWiki\\",
		"lib": "C:\\Data\\lib"
    },
    "types":{
        "htmlfile": ["htm", "html", "hta"]
    },
    "username": "",
    "password": "",
    "host": "0.0.0.0",
    "port": 8088,
    "backupDirectory": "C:\\Data\\TW5\\backups", 
    "etagWindow": 8,
    "etag": "",
    "useTW5path" : false
}

```

**Comment by Arlen22** [comment]
Etag window only applies to the time modified, not file size. This is a
little strange. There is a setting to disable it entirely if desired. It
should be in the docs. But size will always indicate a change. Not sure why
it's changing though.
