### ISSUE TITLE
Use of ifaces = os.networkInterfaces

### ISSUE THREAD

**Issue by JonathanDoughty** [Arlen22/TiddlyServer#5]
By default TiddlyServer is going to effectively broadcast / make accessible **all** the TW contents it supports on the local area network.  You might want to document the "host" (and "port") settings.json possibilities and warn users. Better yet, I suggest including "host": "127.0.0.1" - the reserved loopback address - in the example settings.json file would be a better default, non-routable option in my opinion; see https://serverfault.com/a/839462 and that, if no value "host" key is present in settings.json default to "127.0.0.1" 

One could see using the `ifaces = os.networkInterfaces` that TiddlyServer discovers as a feature, however. On my home network, for example, the current default handling makes TiddlyServer-served contents accessible to / editable from my other devices, like my phone or tablet as well as the laptop where it is installed. So I would not eliminate this option, just make sure users are aware they **may** be making their TW contents accessible by anyone on the same network: wives, children, neighbors if they have not locked down their firewall, or potentially fellow coffee shop patrons. Perhaps TiddlyServer could discover the network interfaces - for those that would like that and have been suitably warned about the implications - by checking for a "host": "discover" key/value pair in settings.json. Then TiddlyServer could default to being secure or open as a user choice. 

I can attempt a PR if you'd like, though my JavaScript is not strong.

**Comment by Arlen22** [comment]
>I can attempt a PR if you'd like, though my JavaScript is not strong.

Thanks, this is a simple change, and I think I got it. I also added 127.0.0.1 as a hard-coded default in case host is not specified. I updated example-settings.json with the new defaults.

**Comment by Arlen22** [comment]
>One could see using the `ifaces = os.networkInterfaces` that TiddlyServer discovers as a feature, however. 
Perhaps TiddlyServer could discover the network interfaces - for those that would like that and have been suitably warned about the implications - by checking for a "host": "discover" key/value pair in settings.json. Then TiddlyServer could default to being secure or open as a user choice.

This is just a feature that tells you what IP address you can access the server from. If there is a host specified, other than `0.0.0.0`, it will just list that host without any discovery.

**Comment by JonathanDoughty** [comment]
That will do. One thing to note: if the host value is set to 0.0.0.0 then TiddlyServer will serve on **all** network interfaces. That results in it using both my wired and wireless interfaces since both are active:

> Settings file: /Users/jwd/CM/TW/settings.json
> Open you browswer and type in one of the following:
> 192.168.1.14:9000
> 192.168.1.17:9000
> twboot: 4918.068ms

Should `ifaces[dev].forEach(` stop once it has found an active interface? Or maybe this is intentional since the log message says "Open you browswer and type in **one** of the following".  I don't want to think / test what happens if the same tiddler is accessed/modified from browsers/devices using different interfaces. Thanks!

**Comment by Arlen22** [comment]
No, the `ifaces[dev].forEach` thing only is telling you information. If you listen on `0.0.0.0` it will _list_ all the network interfaces on the computer, since normally the server can be accessed through any of these. Most of the time it is only one IP address, or in your case two. What actually determines what is being used is the host string that is passed to the http server. The list of IP addresses is just there for convenience sake.

>One thing to note: if the host value is set to 0.0.0.0 then TiddlyServer will serve on all network interfaces.

Well, that is the point. Maybe I should state it explicitly.

>I don't want to think / test what happens if the same tiddler is accessed/modified from browsers/devices using different interfaces. 

Should be the same thing that happens if you access from different browsers using the same interface. The server just sees a request and doesn't care which interface it came in on. Shouldn't be a problem.

**Comment by JonathanDoughty** [comment]
I'm satisfied.
