### ISSUE TITLE
Alternative File Extension for TiddlyWiki Files

### ISSUE THREAD

**Issue by AnthonyMuscio** [Arlen22/TiddlyServer#51]
Hi Arlen,

I was wondering if you could consider my request here, which would open up additional uses for TiddlyWiki as easy to share smart documents. I would love to have TiddlyServer supporting this as well, and I believe it should be a trivial change. The Standard save supports saving as .tw files, as is Timimi.

Could you please review [Alternative File Extension for TiddlyWiki Files #3719](https://github.com/Jermolene/TiddlyWiki5/issues/3719) with a view to allowing TiddlyServer to serve single File wikis with the .tw extension just as it does .htm and .html files?

In tiddlyserver I can't open it because we get the following dialogue 
![tsopen](https://user-images.githubusercontent.com/31584658/51511792-cd2fe680-1e56-11e9-82ed-e5743e668dd7.jpg)
which then seems to open a tempfile eg file:///C:/Users/USERNAME/AppData/Local/Temp/empty-2.tw rather than the actual file in place as for regular TiddlyWikis.

I can browse to such files as below but not open as a wiki .tw or .hta files

```
    "types":{
        "htmlfile": ["htm", "html", "hta", "png", "tw"]
```

**Comment by Arlen22** [comment]
For TiddlyServer, this is probably as simple as setting the content-type header to `text/html` for these files, which probably makes most browsers ignore the file extension and just treat them all as HTML. Is this what you want? Or is there a special content-type that needs to be set for certain extensions?

**Comment by AnthonyMuscio** [comment]
Arlen, I expect thats all we need, will this result in tiddlyserver being able to open and serve them?

I can already open and use them in the browser and save backup with the default saver and Timimi the new tiddlyfox addon.

Thanks for considering this, Tony

**Comment by AnthonyMuscio** [comment]
Arlen. An update. On TiddlyServer v2.0.14

Adding tw as above results in the .tw files (Standard wiki with alternate extension)  listing in TiddlyServer directories (or would they anyway?). In both FF and Chrome instead of opening it in a tab and serving it at the TiddlyServer IP Address it offers to open in the default browser (only works because I have Timimi installed) or download/save the file.

Thanks in advance
Tony

**Comment by AnthonyMuscio** [comment]
I will just add "instead of opening it in a tab and serving it " it opens as a File://path

**Comment by Arlen22** [comment]
This is now supported with the directoryIndex.mimetypes setting in version 2.1.

**Comment by AnthonyMuscio** [comment]
Thank you
