### ISSUE TITLE
Need to rename settings-2-1.schema

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#57]
I installed the newest TS. I upgraded the settings.json file. I upgraded to node.js vsn 10.15.3.

I get the error below. I think it's looking for the wrong settings.schema.json file. After renaming settings-2-1.schema to settings.schema.json I re-ran and the server worked. It might be good to either mention this in the documentation, or perhaps the settings upgrader needs to be tweaked?

The example "branch" which I retained from the original example JSON settings file appears without an icon on the tree home page.

It looks to me like you can now serve files from below the data-folder start directory. I don't believe that was possible before -- great!

----
C:\Apps\TiddlyServer-2.1.1-beta>node server.js
Settings file: C:\Apps\TiddlyServer-2.1.1-beta\settings.json
(node:11972) [DEP0005] DeprecationWarning: Buffer() is deprecated due to securit
y and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or
Buffer.from() methods instead.
(node:11972) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\App
s\TiddlyServer-2.1.1-beta\settings.schema.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadSettings (C:\Apps\TiddlyServer-2.1.1-beta\src\server-types.ts:
149:39)
    at server.libsReady.then (C:\Apps\TiddlyServer-2.1.1-beta\server.js:18:45)
(node:11972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:11972) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

**Comment by Arlen22** [comment]
Thank you, done :)
