### ISSUE TITLE
TiddlyServer still gleaning 127.0.0.1 when another IP Address is used

### ISSUE THREAD

**Issue by AnthonyMuscio** [Arlen22/TiddlyServer#61]
Hi Arlen, Thanks again for the great TiddlyServer.

I have added an additional IP Address to my computer and hosted TiddlyServer on that address, as specified in my full settings.json below. This works well since now I can access tiddlyServer at http://192.168.1.81 (throughout my LAN) without any port number as http defaults to 80. I can also move the IP address to another computer and all my link addresses will not change and I can use dns to map ts.local to this address. All Good, with a minor bug?

The intention however was to free the Computers "primary IP Address" so TiddlyServer was not taking 127.0.0.1:80 however it continues to do so.

**Is this a bug or is there a way to configure around this, so TiddlyServer only appears on http://192.168.1.81?** and not on local host

Thanks in advance

```
{
    "tree": {
	    "Home": "C:\\Data\\TW5\\Hosting\\TiddlyServer-2.0.14\\index.html",
		"Instances": "C:\\Data\\TW5\\Instances",
		"IndexWikis": "C:\\Data\\TW5\\indexWikis",
		"PSaT Business": "C:\\Data\\TW5\\PSaT",
		"PSaT Development": "C:\\Data\\TW5\\PSaTDev",
		"Development": "C:\\Data\\TW5\\Development",
		"EmptyWikis": "C:\\Data\\TW5\\EmptyFiles",
		"Clients": "C:\\Users\\antho\\Documents\\Business\\PSaT\\Clients",
        "WebDav": "C:\\Users\\Public\\Documents\\tw",
	    "Node": "C:\\Data\\TW5\\NodeJS",
        "Editions": "C:\\Data\\TW5\\editions",
		"Pictures": "C:\\Users\\antho\\Pictures\\TiddlyWiki\\",
		"!Root": "C:\\Users\\antho\\Documents\\!Root",
		"lib": "C:\\Data\\lib"
    },
    "types":{
        "htmlfile": ["htm", "html", "hta", "png", "tw"]
    },
    "username": "",
    "password": "",
    "host": "192.168.1.81",
    "port": 80,
    "backupDirectory": "C:\\Data\\TW5\\backups", 
    "etagWindow": 10,
    "etag": "",
    "useTW5path" : false
}
```

**Comment by AnthonyMuscio** [comment]
Actually in looks like all nodeJS based sites try and do this.

**Comment by Arlen22** [comment]
Add _disableLocalHost: true to settings.json to stop this from happening.
TiddlyServer v2.1 will not do this anymore.

**Comment by AnthonyMuscio** [comment]
Thanks, I did not realise I had failed to upgrade from 2.0.14 so will do now

Edit: I see that is the next release not the latest. Thanks
Thanks
Tony
