### ISSUE TITLE
bring-up issues

### ISSUE THREAD

**Issue by jahbini** [Arlen22/TiddlyServer#62]
A couple of caveats with the current master: 
1) the identifier 'format' is used for two different, conflicting purposes in the DebugLogger function in source file src/server-types.ts at line 380.
2) npm versions of dev dependencies is critical -- stick with the ones in the lockfile -- 'formidable' at 1.1.1, 'ws' version 5.0.1 and typescript@3.2.2 were critical to get it going.

However, I am clueless about how the login/auth mechanism works with the spec file.

Any help is appreciated

**Comment by Arlen22** [comment]
Thank you. I will try to make sure the dependancies are taken care of. Normally I don't need to touch them and I have them bundled using webpack. So everything should just work without installing any dependancies. 

I've fixed the format identifier bug, thank you :)

Thank you for asking about the login mechanism. I will include some documentation on that in the near future.
