### ISSUE TITLE
Checkmark doesn't indicate saved status for single files

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#64]
When saving a single file, the file doesn't know that it has been saved. That is, the check mark remains red.  Clicking on it a second time will result in an actual RSOE with a message about xhr. The first save appears to actually work, it's just a matter of sending the message back to the button. Also, when leaving the page it will prompt you to save changes even though the changes have been saved

**Comment by Arlen22** [comment]
What version of TiddlyServer (shown at the bottom of the directory index) are you using and what version of TiddlyWiki is the single-file wiki you are trying to edit (you can find it somewhere in the Control Panel)?

**Comment by ChrisLMerrill** [comment]
I'm seeing similar behavior with TS v2.1.1-beta and a TW 5.1.20 file.

**Comment by ChrisLMerrill** [comment]
Let me amend that:
1. I see the same behavior (save icon doesn't indicate save status) with TS v2.1.1-beta and a TW 5.1.13 file. This seems like new behavior to me, perhaps triggered by a change in Firefox (I've been using this wiki nearly daily for many months...not sure when the change started)
2. With a TW 5.1.20 file, I see the same, but clicking the save button results in a "file changed on server" message (though the save appears successful).

**Comment by Arlen22** [comment]
This should be fixed now in master. Please reopen if you experience further issues.
