### ISSUE TITLE
Documentation: Which binary do you mean?

### ISSUE THREAD

**Issue by TiddlyTweeter** [Arlen22/TiddlyServer#7]
Ciao Arlen

I'm unclear about WHICH binary you mean in this from the documentation ...

> Download the latest release of TiddlyServer from https://github.com/Arlen22/TiddlyServer/releases unzip the folder contained in the zip file to wherever you want it. **Put the binary in this folder if you want it to be portable.**

**Comment by Arlen22** [comment]
Changed it to "Put the NodeJS binary in this folder if you want it to be portable." 

Does that make more sense?

**Comment by TiddlyTweeter** [comment]
Much better. I noticed that what you actually wrote was **Put the NodeJS binary (node.exe) in this folder if you want it to be portable**, which is even better.
