### ISSUE TITLE
getting started 404

### ISSUE THREAD

**Issue by CaiBaoHong** [Arlen22/TiddlyServer#75]
I download the release [v2.1.5](https://github.com/Arlen22/TiddlyServer/archive/v2.1.5.tar.gz) and `tar -xf v2.1.5.tar.gz`

then add `settings.js` to folder `TiddlyServer-2.1.5` with the follow content:
~~~json
{
	"tree": "../webroot",
	"bindInfo": {"bindAddress": ["127.0.0.1"]},
	"putsaver": {"backupFolder": "../backups"},
	"$schema": "./settings-2-1.schema.json"
}
~~~

I also add a folder called `webroot` in folder `TiddlyServer-2.1.5`.

then I run `node server.js`，but I can't see anything in the browser, the terminal log like this:
~~~bash
caibh@company:~/TiddlyServer-2.1.5$ node server.js
Settings file: /home/caibh/TiddlyServer-2.1.5/settings.json
Creating servers as http
Remember that any login credentials are being sent in the clear
 SERVER  2019-10-09 12:07:38 server 127.0.0.1 listening
Open your browser and type in one of the following:
http://127.0.0.1:8080
[2019-10-09T12:07:51.036+-800] GET     127.0.0.1       404 127.0.0.1 /                                                           13.587 ms - -
[2019-10-09T12:07:53.729+-800] GET     127.0.0.1       404 127.0.0.1 /                                                           1.262 ms - -
~~~

What did i missed ?

**Comment by Arlen22** [comment]
`../webroot` would be sibling to the TiddlyServer folder, not to the settings.json file, so it needs to be outside of the TiddlyServer folder.

**Comment by Arlen22** [comment]
Two dots is obviously the "relative parent" operator. Sorry, should have made that clearer.

**Comment by CaiBaoHong** [comment]
> Two dots is obviously the "relative parent" operator. Sorry, should have made that clearer.

Thanks, it works now !
