### ISSUE TITLE
Backups not happening

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#78]
I have a file that gets written to every day (see below). Today I needed to find a backup (note the corrupt 20 byte file). To my surprise, the most recent backup was from 6 days ago. It appears that either backup files are not being made, or some interim files are being automatically cleared out. If so, what setting could prevent that?

Windows 7, Firefox 70.0.1

Backup setting:

> 	"backupFolder": "C:\\temp\\twbackups"

Thanks!

> _Wikis_bible_Bible_html-1573962550000.gz	2.06 MB	11/16/2019 8:45:42 PM	ACDSee 9.0 GZIP Archive	A
_Wikis_bible_Bible_html-1573444151000.gz	20 Byte(s)	11/16/2019 7:49:07 PM	ACDSee 9.0 GZIP Archive	A
_Wikis_bible_Bible_html-1573361236000.gz	2.06 MB	11/10/2019 7:49:10 PM	ACDSee 9.0 GZIP Archive	A

**Comment by Arlen22** [comment]
No files are cleared by TiddlyWiki and backups are always made if a backup folder is set. It is possible that some errors are being silently ignored. I will make this section more robust in case this is the case, but in most cases a backup error will cause the save to fail.
