### ISSUE TITLE
broken image icon

### ISSUE THREAD

**Issue by JonathanDoughty** [Arlen22/TiddlyServer#8]
Within the tree definition in my settings.json I have:

```
    "tree": {
        "projects": {
            "project1": "/path/to/project1",
            "project2": "/path/to/project2",
            ...
        },
    },
```

For the projects 'subfolder', of type category, the generated HTML is:

```
<tr class="row even category">
    <td><span class="icon"><img src="/icons/category.png"/></span></td>
```

category.png is NOT included in the git repo that I get on fetch; so my top level TiddlyServer page ends up with a broken image icon that looks like: 
![image](https://user-images.githubusercontent.com/1918593/27937889-635a9876-6288-11e7-8518-18aa748d40d7.png)
and the log ends up with a 404:
`1940:[2017-07-05T22:18:49.717-0400] GET 404 127.0.0.1 /icons/category.png`

I suspect that icon should be referencing folder.png, not category.png, and that the problem is in https://github.com/Arlen22/TiddlyServer/blob/master/generateDirectoryListing.js#L13-L16 

As a separate, too minor to open, issue, you might consider adding a version string or some other identifying information (tag, git hash) in the TiddlyServer generated page so it is apparent what version people have.

**Comment by Arlen22** [comment]
>As a separate, too minor to open, issue, you might consider adding a version string or some other identifying information (tag, git hash) in the TiddlyServer generated page so it is apparent what version people have.

Thank you. I will try update package.json from 2.0.5 forward. My apologies for this oversight.

>I suspect that icon should be referencing folder.png, not category.png,

It is intended to be `category.png`, but somehow I forgot to find an icon for it. If you want, you can copy `folder.png` and name it `category.png`.

If you have better icon ideas, let me know.

**Comment by Arlen22** [comment]
https://github.com/Arlen22/TiddlyServer/commit/834b0054d85f78d67f4195c74e2c737a1bd1d939
