### ISSUE TITLE
TidddlyServer looks for group.png icon in /assets/icons/files/ but the png file is in /assets/icons/

### ISSUE THREAD

**Issue by JulioCantarero** [Arlen22/TiddlyServer#80]
I think this is a minor bug, but just FYI. I configured TS grouping a few datafolders, and the group icon shows as a broken image. The cause seems to be that group.png is not where TS expects.
TidddlyServer looks for group.png icon in /assets/icons/files/ but the png file is in /assets/icons/
See log message:
GET     127.0.0.1       404 127.0.0.1 /assets/icons/files/group.png

**Comment by Arlen22** [comment]
Thanks, I fixed this I think.
