### ISSUE TITLE
Possible typo in info message when running `node server.js` from command line

### ISSUE THREAD

**Issue by altugozcelikkale** [Arlen22/TiddlyServer#9]
`browser` is mispelled as `browswer`  (unless it is intentional that way) in the info message that shows up when `node server.js` is executed.
```
$ node server.js
Settings file: ...
Open your browswer and type in one of the following:
127.0.0.1:8080
```
It is certainly a very minor issue, but just wanted to point out since this shows up every time that command is executed.

Thank you for this amazing piece of software!

**Comment by Arlen22** [comment]
Fixed, thank you
